SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

##COMBINE BOTH TABLES:
SELECT CUSTOMERS.CUSTOMER_NAME, ORDERS.ORDER_ID, OORDERS.ORDER_AMOUNT
FROM CUSTOMERS 
INNER JOIN ORDERS 
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

##AGGREGATE ANALYSIS(TOTAL SPENDING)
SELECT CUSTOMER_NAME,
SUM(ORDERS.ORDER_AMOUNT) AS TOTAL_AMOUNT
FROM CUSTOMERS 
INNER JOIN ORDERS 
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMERS.CUSTOMER_NAME;

##SUBQUERY(ABOVE AVERAGE ORDERS)
SELECT CUSTOMER_ID, ORDER_AMOUNT
 FROM ORDERS
 WHERE ORDER_AMOUNT >
 (SELECT AVG(ORDER_AMOUNT) FROM ORDERS);

##CTES
WITH CUSTOMER_TOTAL AS
(
   SELECT C.CUSTOMER_NAME,
          SUM(O.ORDER_AMOUNT) AS TOTAL_AMOUNT
   FROM CUSTOMERS C
  INNER JOIN ORDERS O
   ON C.CUSTOMER_ID = O.CUSTOMER_ID
   GROUP BY C.CUSTOMER_NAME
)
SELECT * FROM CUSTOMER_TOTAL;

##WINDOW FUNCTION(RANKING CUSTOMERS)
WITH CUSTOMER_TOTAL AS
(
   SELECT C.CUSTOMER_NAME,
    SUM(O.ORDER_AMOUNT) AS TOTAL_AMOUNT
   FROM CUSTOMERS C
 INNER JOIN ORDERS O
   ON C.CUSTOMER_ID = O.CUSTOMER_ID
   GROUP BY C.CUSTOMER_NAME
)
SELECT CUSTOMER_NAME,
       TOTAL_AMOUNT,
       RANK() OVER (ORDER BY TOTAL_AMOUNT DESC) AS CUSTOMER_RANK
FROM CUSTOMER_TOTAL;

##Running Total (Trend Analysis)
SELECT ORDER_ID,
       ORDER_AMOUNT,
       SUM(ORDER_AMOUNT) OVER (ORDER BY ORDER_ID) AS RUNNING_TOTAL
FROM ORDERS;






